{
    'name': "Hospital Manager",
    'summary': """Hospital Manager""",
    'description': """test odoo""",
    'sequence': "-10",
    'author': "Dung",
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': [
        'sale',
        'mail',
        'website_slides',
        'hr',
    ],
    'data': [
        "security/ir.model.access.csv",
        "data/data.xml",
        # "data/slide_data_v12.xml",
        # "data/slide_data_v13.xml",
        # "data/slide_data_v14.xml",
        # "data/slide_data_v12_2.xml",
        "wizard/create_appointment_view.xml",
        "views/patient_view.xml",
        "views/patient_gender_view.xml",
        "views/kids_view.xml",
        "views/sale.xml",
        "views/appointment_view.xml",
    ],
    # 'qweb': ['static/src/xml/*.xml'],
    'installable': True,
    'application': True,
}
